// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos-2pc.proto

package org.cse535.proto;

public final class Paxos2Pc {
  private Paxos2Pc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransactionInputConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransactionInputConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TxnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TxnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActivateServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActivateServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActivateServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActivateServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeactivateServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeactivateServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeactivateServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeactivateServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandOutput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017paxos-2pc.proto\032\037google/protobuf/times" +
      "tamp.proto\"q\n\026TransactionInputConfig\022\021\n\t" +
      "setNumber\030\001 \001(\005\022!\n\013transaction\030\002 \001(\0132\014.T" +
      "ransaction\022\014\n\004view\030\003 \001(\005\022\023\n\013serverNames\030" +
      "\005 \003(\t\"\265\001\n\013Transaction\022\016\n\006sender\030\001 \001(\005\022\020\n" +
      "\010receiver\030\002 \001(\005\022\016\n\006amount\030\003 \001(\005\022-\n\ttimes" +
      "tamp\030\004 \001(\0132\032.google.protobuf.Timestamp\022\027" +
      "\n\017transactionHash\030\005 \001(\t\022\026\n\016transactionNu" +
      "m\030\006 \001(\005\022\024\n\014isCrossShard\030\007 \001(\010\"2\n\013TxnResp" +
      "onse\022\017\n\007success\030\001 \001(\010\022\022\n\nserverName\030\002 \001(" +
      "\t\"+\n\025ActivateServerRequest\022\022\n\nserverName" +
      "\030\001 \001(\t\"=\n\026ActivateServerResponse\022\017\n\007succ" +
      "ess\030\001 \001(\010\022\022\n\nserverName\030\002 \001(\t\"-\n\027Deactiv" +
      "ateServerRequest\022\022\n\nserverName\030\001 \001(\t\"?\n\030" +
      "DeactivateServerResponse\022\017\n\007success\030\001 \001(" +
      "\010\022\022\n\nserverName\030\002 \001(\t\"\035\n\014CommandInput\022\r\n" +
      "\005input\030\001 \001(\t\"\037\n\rCommandOutput\022\016\n\006output\030" +
      "\001 \001(\t2;\n\005Paxos\0222\n\007Request\022\027.TransactionI" +
      "nputConfig\032\014.TxnResponse\"\0002\241\001\n\017ActivateS" +
      "ervers\022C\n\016activateServer\022\026.ActivateServe" +
      "rRequest\032\027.ActivateServerResponse\"\000\022I\n\020d" +
      "eactivateServer\022\030.DeactivateServerReques" +
      "t\032\031.DeactivateServerResponse\"\0002\304\001\n\010Comma" +
      "nds\022/\n\014printBalance\022\r.CommandInput\032\016.Com" +
      "mandOutput\"\000\022+\n\010printLog\022\r.CommandInput\032" +
      "\016.CommandOutput\"\000\022*\n\007printDB\022\r.CommandIn" +
      "put\032\016.CommandOutput\"\000\022.\n\013Performance\022\r.C" +
      "ommandInput\032\016.CommandOutput\"\000B\024\n\020org.cse" +
      "535.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_TransactionInputConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransactionInputConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransactionInputConfig_descriptor,
        new java.lang.String[] { "SetNumber", "Transaction", "View", "ServerNames", });
    internal_static_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Transaction_descriptor,
        new java.lang.String[] { "Sender", "Receiver", "Amount", "Timestamp", "TransactionHash", "TransactionNum", "IsCrossShard", });
    internal_static_TxnResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TxnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TxnResponse_descriptor,
        new java.lang.String[] { "Success", "ServerName", });
    internal_static_ActivateServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ActivateServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActivateServerRequest_descriptor,
        new java.lang.String[] { "ServerName", });
    internal_static_ActivateServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ActivateServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActivateServerResponse_descriptor,
        new java.lang.String[] { "Success", "ServerName", });
    internal_static_DeactivateServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_DeactivateServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeactivateServerRequest_descriptor,
        new java.lang.String[] { "ServerName", });
    internal_static_DeactivateServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_DeactivateServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeactivateServerResponse_descriptor,
        new java.lang.String[] { "Success", "ServerName", });
    internal_static_CommandInput_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_CommandInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandInput_descriptor,
        new java.lang.String[] { "Input", });
    internal_static_CommandOutput_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_CommandOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandOutput_descriptor,
        new java.lang.String[] { "Output", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
